language: cpp
compiler: gcc

env: CMAKE_CMD_OPTION="-DENABLE_TESTING=1 "

jobs:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      env: CMAKE_CMD_OPTION="-DENABLE_COVERAGE=1"

cache:
  apt: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libboost-dev
      - libboost-test-dev
      - libboost-chrono-dev
      - libboost-date-time-dev
      - libboost-iostreams-dev
      - libboost-system-dev
      - libboost-filesystem-dev
      - libboost-regex-dev
      - lcov
  snaps:
    - name: cmake
      confinement: classic
      channel: 3.17/stable

script:
  - export PATH=/snap/bin:${PATH}
  - cmake --version
  - mkdir build
  - cd build
  - cmake .. $CMAKE_CMD_OPTION
  - make -j 2
  - make test

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

notifications:
  email: false